version: '3'
services:
  app:
    image: node:14
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
    working_dir: /app
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    command: npm start